### ISSUE TITLE
DVMEGA

### ISSUE THREAD

**Issue by CyClore** [nostar/dudestar#100]
This appears as a dvmega to the network.  Can you give this a different name so it is easier to query the network to know who all is using this app?

**Comment by nostar** [comment]
Since you didn't bother to provide any details, I will assume you mean DMR networks.  You don't get to pick any value you want for the product ID text field.  There are only a few select strings that will allow connections to various networks, including MMDVM_DVMEGA and MMDVM_Unknown.  I'll probably switch to MMDVM_Unknown in the future.  I don't know if any networks will add a new string for this software, but if they do, I'll use it.  I'm not too concerned about though, since to me this software is a diagnostic network test tool.
