### ISSUE TITLE
Error on compiling on mac os

### ISSUE THREAD

**Issue by joe-azzara** [nostar/dudestar#12]
Hello,

I get this error on compiling. What I do after installing dependency's
there are no instructions for mac osx

Thank you

**Comment by nostar** [comment]
What error?

**Comment by KC2UBG** [comment]
git clone https://github.com/nostar/dudestar.git
cd dudestar
mkdir build
cd build
qmake 
and nothing happens

**Comment by nostar** [comment]
Where did the mkdir build and cd build come from?  Just run qmake and make from the dudestar directory.  There are no mac osx instructions because I am not aware of anything mac osx specific.  I do not have a mac though, so I only know that mac users have reported that it builds and runs with the mac osx build tools (XCode?) and mbelib.

**Comment by KC2UBG** [comment]
command not found: qmake

**Comment by KC2UBG** [comment]
I did run qmake and make from the dudestar directory and nothing happen?

**Comment by nostar** [comment]
Dudestar is a Qt5 program, it looks like you dont have Qt5, or mac osx calls qmake something else.  I don't have mac osx so I cant help there, but for example on Fedora Linux the qmake executable is called qmake-qt5.

**Comment by KC2UBG** [comment]
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [dudestar.app/Contents/MacOS/dudestar] Error 1

**Comment by nostar** [comment]
This means that you compiled and installed mbelib from source, but as a locally built library, your operating system installed the library files to a non-standard location.  This location is pretty much always /usr/local/lib and/or /usr/local/lib64 on unix/linux systems.  Since OSX is unix based, it is probably the same.

First make sure that the libmbe* files are in /usr/local/lib and/or /usr/local/lib64

Then create a file called local.conf in /etc/ld.so.conf and add 2 lines:
/usr/local/lib
/usr/local/lib64

Save and close the file.  It doesn't matter if one of these direcotries was empty or even if one of them was non existent.

then run the command 'ldconfig'

All of these needs root permissions, obviously.  Once this is all done run make again and it should find the mbelib files and link successfully.

**Comment by rd0fun** [comment]
Has anyone been able to successfully build dude-star on MacOS yet? Could you share how you did it please?

**Comment by rd0fun** [comment]
I think I have made progress. Software is running and receiving natively on MacOS!
I have not confirmed that it actually transmits.

**Comment by rd0fun** [comment]
> ld: warning: directory not found for option '-LC:Qt5.14.0mingw73_32_staticlib'
> ld: library not found for -lmbe
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [dudestar.app/Contents/MacOS/dudestar] Error 1

The Makefile has some static paths in it. You hit one. The makefile has "C:\..." for example. That will trip up anything but a PZC of course.

**Comment by nostar** [comment]
It is ok to have this path in there because the -L option only adds the path to the existing list of locations to check.  I keep that path in there for Windows builds, where I do not install mbelib, instead just build it and manually place the library file in that directory.  In your case, assuming that you built and installed mbelib from source, you will need to tell your linker where to find the library files.  See my post on this issue from May 25 where I explain how to do that.

I am confused though when you say that you are running and receiving on MacOS, because it will not build without mbelid, and this lib is specifically for software ambe decoding.

**Comment by rd0fun** [comment]
I have git cloned the mbelib and did a make install on it. That library is on my system.

Is there a way for me to set up some sort of parrot to test transmission? (yes, I really am 'that new' to DMR!)

**Comment by TychoSchenkeveld** [comment]
> I have git cloned the mbelib and did a make install on it. That library is on my system.
> 
> Is there a way for me to set up some sort of parrot to test transmission? (yes, I really am 'that new' to DMR!)

In BM this is supposed to be possible with 9990: https://wiki.brandmeister.network/index.php/Parrot . But when I tried it a message in Spanish comes and tells me I'm doing something wrong and my Spanish isn't that good yet ;) But on your master server this may work!

**Comment by nostar** [comment]
Click 'Private' when transmitting into BM 9990.

**Comment by TychoSchenkeveld** [comment]
Thanks nostar! I overlooked that tickbox, sorry 👍 

By the way I have the same issue as rd0fun indeed. Outgoing transmissions are garbled with mbelib, incoming is fine.

**Comment by djshadowxm82** [comment]
I can also confirm this is an issue and built similarly. Receive is working but it does not transmit properly. It is completely garbled. Any tests we can try to work through to see if there is something amiss on mac vs a linux build?

**Comment by nostar** [comment]
Open a new issue for this.  This one was for a compiling issue.

**Comment by djshadowxm82** [comment]
> Open a new issue for this. This one was for a compiling issue.

Will do thanks, sorry to reopen. Will reference.
