### ISSUE TITLE
NEED HELP PLEASE !!!

### ISSUE THREAD

**Issue by hpaineiv** [nostar/dudestar#150]
DMR connection refused.  Check callsign, DMR ID, ESSID, and hotspot security password.  Some servers require specific information for Lat/Long/Location/Description/Freq/URL/Software ID/Package ID, namely BrandMeister.  It's up to you to determine this information from the server you are attempting to connect to.

I HAVE ENTERED ALL THE CORRECT INFO 
CALLSIGN 
DMR ID
HOTSPOT PASSWORD
NO ESSID
I EVEN TRIED ENTERING MY LAT LON AS IT IS ON BRANDMEISTER.

WHERE DO I FIND SOFTWARE ID AND PACKAGE ID  ???
WHAT ARE THEY ?

I LOVE THIS SOFTWARE AND WOULD EVEN PAY FOR IT ....
NOW IM SAD BECAUSE I CANT CONNECT 
THE PREVIOUS VERSIONS I HAVE STILL WORK BUT IT IS NIVE TO HAVE THE LATEST VERSION !

**Comment by Slayingripper** [comment]
Does this issue persist even when you use a different server ?

**Comment by hpaineiv** [comment]
I cannot connect to dmr
I cannot even reach a server

**Comment by robrobinette** [comment]
It seems Brandmeister has been having problems in the last few days (Mar 4-7 2021) but as of the 7th I am able to transmit to talkgroup 3147 Tennessee using BM_US_3101.

The "DMR Hotspot security password" is not the same thing as your Brandmeister login password. Several people have had your problem because they did not log in to Brandmeister and specifically set a hotspot password. The Brandmeister hotspot password requirement is relatively new.

You can see my DUDE-Star settings and main DMR tabs here: [https://robrobinette.com/Ham_VHF-UHF_Digital_Modes.htm#DUDE-Star_&_DROID-Star](url)

**Comment by nostar** [comment]
This is something Brandmeister is doing, not a Dudestar issue, so take it to the discussions.
