### ISSUE TITLE
talkgroup disconnects between exchanges

### ISSUE THREAD

**Issue by uglybugs** [nostar/dudestar#185]
after selecting a talkgroup # and then holding the TX button for a couple seconds the talkgroup can be monitored.
however, as soon as that person releases the TX button  ( a pause in the conversation )
i am no longer able to hear the responding person's reply unless i momentarily press my TX button.

basically, while monitoring a conversation i have to press my TX button between each pause in their transmissions.
is this normal ? is there a better way to monitor a talkgroup conversation ?

DUDE-Star Windows 64-bit git build 7bc4ac0
Copyright (C) 2019-2021 Doug McLain AD8DP

**Comment by Eszartek** [comment]
I just compiled HEAD 22dd3b7 on Linux and I have the same exact issue. For the heck of it I installed the 64bit version on a Windows laptop as a test and it too would loose the conversation as you noted.

As a third test, I installed DroidStar v0.53-Beta on my phone and that works perfectly. I can't find source for the android build, otherwise I was going to compare it with the Linux source, perhaps I could find the commit that breaks reception.

**Comment by Eszartek** [comment]
On windows it did not work at first after changing those two parameters. Then I switched the Windows setting from slot 1 to Slot 2, restarted and then now its working perfect.

I keep testing, perhaps it was the reconnects that had some effect.
