### ISSUE TITLE
Audio lower than windows

### ISSUE THREAD

**Issue by 2e0ukh** [nostar/dudestar#5]
Chris 2E0UKH testing. Working great all modes. Noticed Even when rx audio is fully up its much quieter than other stuff running on windows.
  I am talking about yr great software on youtube. "Digital Analogue Ham" Channel!

**Comment by nostar** [comment]
Hi Chris, I am skimming through your video and I have some notes:

First of all, DUDE-Star is very beta. There is still much to be desired, like advanced configuration options, etc.  I'm glad you and others are having as much luck with the Windows version as you all are, since my primary platform is Linux.  I have had reports of audio level issues on Windows, so in time I will spend more time looking into the Windows version.

You can run DUDE-Star with or without the AMBE USB device, as your friend Fred discovered.  It does software AMBE decoding when no AMBE hardware is found for receive-only operation (Like my Droidstar android app), of all modes *except* P25.  The AMBE3000 chip used on all of these USB devices does not support P25, but DUDE-Star does both software decoding *and* encoding for P25, so you can RX and TX P25 with no AMBE hardware.  This is why Fred was able to TX with you on P25, even though I dont think he had his mic settings correct, as you pointed out.

Software decoding allows you to run multiple instances of DUDE-Star to monitor multiple reflectors/hosts at the same time. 

You do not need a P25 or NXDN ID, it just uses your DMR ID.

When you first connected to NXDN, that small chuck of audio that you heard was just a fragment of RX audio left in the queue from the last connection.  That is a bug that I am aware of.

Cool video, thanks for the positive review!

**Comment by 2e0ukh** [comment]
Thank you for the email. Feel free to let me know of any developments my viewers may be interested in. Regards 2e0ukh@gmail.com

**Comment by nostar** [comment]
Closing

**Comment by JohnWJ69** [comment]
Hi there where can I get the software and is it easy to install and use for a dummy to use
