### ISSUE TITLE
Connecting to hosts

### ISSUE THREAD

**Issue by VE2DMR** [nostar/dudestar#59]
As a Canadian resident, The DMR BM_3021...works fine...But unable to connect with ipsc2_Can-trbo...
Changing my ip address to a US one via VPN server...I can now connect to that Cdn Host.
It appears that the source IP restricts usage.
My 2 cents
73
R

**Comment by nostar** [comment]
What does this have to do with dudestar?

**Comment by VE2DMR** [comment]
Well, if you can not connect to host - your app is useless - I would think...

G

**Comment by Slayingripper** [comment]
So what you are saying VE2DMR is that you can't connect to IPSC2-CAN-TRBO using the application , but it works when you use a VPN it works fine ? So that would indicate that it is you who has the problem not the application. I've just connected up to IPSC2-CAN-TRBO just fine with no VPN , so if I where you I would check my network settings.
