### ISSUE TITLE
Failed to register at Brandmeister when ESSID was set

### ISSUE THREAD

**Issue by sa2kaa** [nostar/dudestar#85]
The "client" failed to register properly at BM with field set to 5. When I removed the entry traffic from TG91 started. I received no error message about registering failure and from the log dialog it seemed to be connected.

**Comment by nostar** [comment]
This doesn't make any sense.  What is a registering failure? You *were* connected when ESSID was set, but as a different DMRID. That's how ESSID works.  This is not a Dudestar issue.

**Comment by sa2kaa** [comment]
I had a pi-start hotspot concurrently connected using a different ESSID and I could observe that it received calls from TG91 while dude-star did not. On the other hand. I have failed to understand how to set talk group in dude-start. It seems like it uses static linked grops from BM.

**Comment by nostar** [comment]
That is exactly how it is supposed to work.  A different ESSID in dudestar makes your connection to BM a connection from a completely different DMR ID. That is the purpose of the ESSID.  You have to TX from that different ESSID in order to link the TG you want to that different ESSID.  This is just like a hotspot.

**Comment by sa2kaa** [comment]
Oh, is see, pi-star has that feature too but usually set up several static TG's. I guess I make the feature of setting static groups at BM a proposal then.
